/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pm.project;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class EditDataKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form EditDataKaryawan
     */
    public EditDataKaryawan() {
        initComponents();
          Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
          int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
   setShape(new RoundRectangle2D.Double(0,0, getWidth(),getHeight(),27,27)); 
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM tb_karyawan INNER JOIN tb_akun ON tb_karyawan.id_karyawan = tb_akun.id_karyawan WHERE tb_karyawan.id_karyawan ='"+Dashboard.selectedKaryawanID+"'");
            while(rs.next()){
                txt_idkaryawan.setText(rs.getString("id_karyawan"));
                txt_nama.setText(rs.getString("nama_karyawan"));
                cmb_jeniskelamin.setSelectedItem(rs.getString("jenis_kelamin"));
                tgllahir.setDate(rs.getDate("tgl_lahir"));
                txt_nohp.setText(rs.getString("no_hp"));
                txt_alamat.setText(rs.getString("alamat"));
                txt_email.setText(rs.getString("email"));
                txt_username.setText(rs.getString("Username"));
                txt_password.setText(rs.getString("password"));
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        txt_idkaryawan = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        cmb_jeniskelamin = new javax.swing.JComboBox<>();
        txt_nohp = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        tgllahir = new com.toedter.calendar.JDateChooser();
        selesai = new javax.swing.JLabel();
        KembaliKaryawan = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        bg = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");
        popupMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupMenu1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_idkaryawan.setBackground(new java.awt.Color(245, 239, 254));
        txt_idkaryawan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_idkaryawan.setBorder(null);
        txt_idkaryawan.setEnabled(false);
        getContentPane().add(txt_idkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 53, 263, 32));

        txt_nama.setBackground(new java.awt.Color(245, 239, 254));
        txt_nama.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_nama.setBorder(null);
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 101, 240, 32));

        cmb_jeniskelamin.setBackground(new java.awt.Color(236, 239, 254));
        cmb_jeniskelamin.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmb_jeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        cmb_jeniskelamin.setBorder(null);
        cmb_jeniskelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_jeniskelaminActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_jeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 148, 265, 34));

        txt_nohp.setBackground(new java.awt.Color(245, 239, 254));
        txt_nohp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_nohp.setBorder(null);
        txt_nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nohpActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 197, 240, 32));

        txt_alamat.setBackground(new java.awt.Color(245, 239, 254));
        txt_alamat.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_alamat.setBorder(null);
        getContentPane().add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 245, 240, 32));

        txt_email.setBackground(new java.awt.Color(245, 239, 254));
        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_email.setBorder(null);
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 292, 240, 32));
        getContentPane().add(tgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 270, 30));

        selesai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selesaiMouseClicked(evt);
            }
        });
        getContentPane().add(selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 70, 20));

        KembaliKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KembaliKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliKaryawanMouseClicked(evt);
            }
        });
        getContentPane().add(KembaliKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 489, 75, 23));

        txt_username.setBackground(new java.awt.Color(236, 239, 254));
        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_username.setBorder(null);
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 389, 240, 30));

        txt_password.setBackground(new java.awt.Color(236, 239, 254));
        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_password.setBorder(null);
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 436, 240, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Input data karyawan (2).png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_jeniskelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_jeniskelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_jeniskelaminActionPerformed

    private void txt_nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nohpActionPerformed

    private void selesaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selesaiMouseClicked
        // TODO add your handling code here:
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
            String id = txt_idkaryawan.getText();
            String nama=txt_nama.getText();
            String jk=cmb_jeniskelamin.getSelectedItem().toString();
            String tampilan = "yyyy-MM-dd";
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            String tanggallahir = String.valueOf(fm.format(tgllahir.getDate()));
            
            try{
                Long.parseLong(txt_nohp.getText());
                String nohp =txt_nohp.getText();
                String alamat=txt_alamat.getText();
                String email=txt_email.getText();
                String username =txt_username.getText();
                String password =txt_password.getText();
               
                PreparedStatement ps = con.prepareStatement("UPDATE tb_karyawan SET nama_karyawan ='"+nama+"', jenis_kelamin = '"+jk+"', alamat = '"+alamat+"', no_hp='"+nohp+"', email = '"+email+"' , tgl_lahir = '"+tanggallahir+"'WHERE id_karyawan = '"+id+"'");
                ps.execute();
                PreparedStatement ps1 = con.prepareStatement("UPDATE tb_akun SET Username ='"+username+"', password = '"+password+"' WHERE id_karyawan = '"+id+"'");
                ps1.execute();
                JOptionPane.showMessageDialog(null,"Data karyawan berhasil diedit");
                Dashboard.loadDataKaryawan();
                dispose();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Masukkan data dengan benar");
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_selesaiMouseClicked

    private void popupMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popupMenu1ActionPerformed

    private void KembaliKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliKaryawanMouseClicked
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_KembaliKaryawanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDataKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KembaliKaryawan;
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox<String> cmb_jeniskelamin;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JLabel selesai;
    private com.toedter.calendar.JDateChooser tgllahir;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_idkaryawan;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nohp;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
