
package pm.project;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class EditLaptopBeli extends javax.swing.JFrame {
    /**
     * Creates new form InputDatabaranglaptop
     */
    Koneksi connect = new Koneksi();
    public EditLaptopBeli() {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
          int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
    setShape(new RoundRectangle2D.Double(0,0, getWidth(),getHeight(),27,27)); 
    try{
       int row = Dashboard.tb_pembelianlaptop.getSelectedRow();
       txt_kodebarang.setText(Dashboard.tb_pembelianlaptop.getValueAt(row, 1).toString());
       txt_namabarang.setText(Dashboard.tb_pembelianlaptop.getValueAt(row, 2).toString());
       txt_processor.setText(Dashboard.tb_pembelianlaptop.getValueAt(row, 3).toString());
       txt_GPU.setText(Dashboard.tb_pembelianlaptop.getValueAt(row, 4).toString());
       txt_RAM.setText(Dashboard.tb_pembelianlaptop.getValueAt(row, 5).toString());
       txt_warna.setText(Dashboard.tb_pembelianlaptop.getValueAt(row, 6).toString());
       txt_jumlah.setText(Dashboard.tb_pembelianlaptop.getValueAt(row, 7).toString());
       txt_hargabeli.setText(Dashboard.tb_pembelianlaptop.getValueAt(row, 8).toString());
   }
   catch(Exception e)
   {
       
   }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_kodebarang = new javax.swing.JTextField();
        txt_jenis = new javax.swing.JTextField();
        txt_namabarang = new javax.swing.JTextField();
        txt_processor = new javax.swing.JTextField();
        txt_GPU = new javax.swing.JTextField();
        txt_RAM = new javax.swing.JTextField();
        txt_warna = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        txt_hargabeli = new javax.swing.JTextField();
        txt_kodetrb = new javax.swing.JTextField();
        selesai = new javax.swing.JLabel();
        KembaliLaptop = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_kodebarang.setBackground(new java.awt.Color(236, 239, 254));
        txt_kodebarang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_kodebarang.setBorder(null);
        txt_kodebarang.setEnabled(false);
        getContentPane().add(txt_kodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 66, 210, 24));

        txt_jenis.setEditable(false);
        txt_jenis.setBackground(new java.awt.Color(236, 239, 254));
        txt_jenis.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_jenis.setText("    Laptop");
        txt_jenis.setBorder(null);
        txt_jenis.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txt_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 105, 210, 24));

        txt_namabarang.setBackground(new java.awt.Color(236, 239, 254));
        txt_namabarang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_namabarang.setBorder(null);
        txt_namabarang.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txt_namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 144, 210, 24));

        txt_processor.setBackground(new java.awt.Color(236, 239, 254));
        txt_processor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_processor.setBorder(null);
        getContentPane().add(txt_processor, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 183, 210, 24));

        txt_GPU.setBackground(new java.awt.Color(236, 239, 254));
        txt_GPU.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_GPU.setBorder(null);
        getContentPane().add(txt_GPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 224, 210, 24));

        txt_RAM.setBackground(new java.awt.Color(236, 239, 254));
        txt_RAM.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_RAM.setBorder(null);
        getContentPane().add(txt_RAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 263, 210, 24));

        txt_warna.setBackground(new java.awt.Color(236, 239, 254));
        txt_warna.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_warna.setBorder(null);
        getContentPane().add(txt_warna, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 301, 210, 24));

        txt_jumlah.setBackground(new java.awt.Color(236, 239, 254));
        txt_jumlah.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_jumlah.setBorder(null);
        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });
        getContentPane().add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 339, 210, 24));

        txt_hargabeli.setBackground(new java.awt.Color(236, 239, 254));
        txt_hargabeli.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_hargabeli.setBorder(null);
        getContentPane().add(txt_hargabeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 377, 210, 24));

        txt_kodetrb.setEditable(false);
        txt_kodetrb.setBackground(new java.awt.Color(236, 239, 254));
        txt_kodetrb.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_kodetrb.setBorder(null);
        txt_kodetrb.setEnabled(false);
        getContentPane().add(txt_kodetrb, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 68, 228, 31));

        selesai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selesaiMouseClicked(evt);
            }
        });
        getContentPane().add(selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 423, 90, 30));

        KembaliLaptop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KembaliLaptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliLaptopMouseClicked(evt);
            }
        });
        getContentPane().add(KembaliLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 65, 20));

        Background.setBackground(new java.awt.Color(236, 239, 254));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/belilaptop.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selesaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selesaiMouseClicked
        try {  
            int row = Dashboard.tb_pembelianlaptop.getSelectedRow();
            Dashboard.tb_pembelianlaptop.setValueAt(txt_kodebarang.getText(), row, 1);
            Dashboard.tb_pembelianlaptop.setValueAt(txt_namabarang.getText(), row, 2);
            Dashboard.tb_pembelianlaptop.setValueAt(txt_processor.getText(), row, 3);
            Dashboard.tb_pembelianlaptop.setValueAt(txt_GPU.getText(), row, 4);
            Dashboard.tb_pembelianlaptop.setValueAt(txt_RAM.getText(), row, 5);
            Dashboard.tb_pembelianlaptop.setValueAt(txt_warna.getText(), row, 6);
            Dashboard.tb_pembelianlaptop.setValueAt(txt_jumlah.getText(), row, 7);
            Dashboard.tb_pembelianlaptop.setValueAt(txt_hargabeli.getText(), row, 8);
            Dashboard._settotalbeli();
            dispose();
            }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Masukkan data dengan benar" );
        }
    }//GEN-LAST:event_selesaiMouseClicked

    private void KembaliLaptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliLaptopMouseClicked
        // TODO add your handling code here:                
        dispose();
    }//GEN-LAST:event_KembaliLaptopMouseClicked

    private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlahActionPerformed

    /**String kodebarang = txt_kodebarang.getText();
        String jenis = txt_jenis.getText();
        String namabarang = txt_namabarang.getText();
        String processor = txt_processor.getText();
        String GPU = txt_GPU.getText();
        String RAM = txt_RAM.getText();
        String warna = txt_warna.getText();
        String jumlah = txt_jumlah.getText();
        String hargaBeli = txt_hargabeli.getText();
        String hargaJual = txt_hargajual.getText();
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditLaptopBeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditLaptopBeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditLaptopBeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditLaptopBeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditLaptopBeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel KembaliLaptop;
    private javax.swing.JLabel selesai;
    private javax.swing.JTextField txt_GPU;
    private javax.swing.JTextField txt_RAM;
    private javax.swing.JTextField txt_hargabeli;
    private javax.swing.JTextField txt_jenis;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_kodebarang;
    private javax.swing.JTextField txt_kodetrb;
    private javax.swing.JTextField txt_namabarang;
    private javax.swing.JTextField txt_processor;
    private javax.swing.JTextField txt_warna;
    // End of variables declaration//GEN-END:variables
}
