/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pm.project;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class EditDataServis extends javax.swing.JFrame {
    
    public EditDataServis() {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
        int row = Dashboard.TableServis.getSelectedRow();
        String id = Dashboard.TableServis.getValueAt(row, 0).toString();
        String namab = Dashboard.TableServis.getValueAt(row, 2).toString();
        String namac = Dashboard.TableServis.getValueAt(row, 1).toString();
        String keluhan = Dashboard.TableServis.getValueAt(row, 3).toString();
        String status = Dashboard.TableServis.getValueAt(row, 6).toString();
               txt_idservis.setText(id);
               txt_namabarang.setText(namab);
               txt_namaclient.setText(namac);
               txt_keluhan.setText(keluhan);
               cmb_status.setSelectedItem(status);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_idservis = new javax.swing.JTextField();
        txt_namabarang = new javax.swing.JTextField();
        txt_namaclient = new javax.swing.JTextField();
        txt_keluhan = new javax.swing.JTextField();
        cmb_status = new javax.swing.JComboBox<>();
        Selesai = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_idservis.setEditable(false);
        txt_idservis.setBackground(new java.awt.Color(236, 239, 254));
        txt_idservis.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_idservis.setBorder(null);
        getContentPane().add(txt_idservis, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 67, 210, 23));

        txt_namabarang.setEditable(false);
        txt_namabarang.setBackground(new java.awt.Color(236, 239, 254));
        txt_namabarang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_namabarang.setBorder(null);
        getContentPane().add(txt_namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 106, 210, 23));

        txt_namaclient.setEditable(false);
        txt_namaclient.setBackground(new java.awt.Color(236, 239, 254));
        txt_namaclient.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_namaclient.setBorder(null);
        getContentPane().add(txt_namaclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 145, 210, 23));

        txt_keluhan.setEditable(false);
        txt_keluhan.setBackground(new java.awt.Color(236, 239, 254));
        txt_keluhan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_keluhan.setBorder(null);
        getContentPane().add(txt_keluhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 184, 210, 23));

        cmb_status.setBackground(new java.awt.Color(236, 239, 254));
        cmb_status.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----Pilih Status----", "Antre", "Proses", "Selesai" }));
        cmb_status.setToolTipText("");
        cmb_status.setBorder(null);
        cmb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_statusActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 225, 210, 23));

        Selesai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Selesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelesaiMouseClicked(evt);
            }
        });
        getContentPane().add(Selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 90, 30));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 70, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Edit Service.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_statusActionPerformed

    private void SelesaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelesaiMouseClicked
        // TODO add your handling code here:
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject", "root", "");
            try{
                String status = cmb_status.getSelectedItem().toString();
                int row = Dashboard.TableServis.getSelectedRow();
                String id = Dashboard.TableServis.getValueAt(row, 0).toString();
                java.sql.Statement st = conn.createStatement();
                String query = ("UPDATE tb_service SET status ='"+status+"' WHERE id_service = '"+id+"'");
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Data Berhasil DiSimpan");
                
                Dashboard.loadDataservis();
                dispose();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Masukkan data dengan benar" );
            }

        } catch (SQLException ex) {
            System.out.print("TERJADI KESALAHAN" + ex);
        }
    }//GEN-LAST:event_SelesaiMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDataServis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDataServis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDataServis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDataServis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDataServis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Selesai;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_idservis;
    private javax.swing.JTextField txt_keluhan;
    private javax.swing.JTextField txt_namabarang;
    private javax.swing.JTextField txt_namaclient;
    // End of variables declaration//GEN-END:variables
}
