/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pm.project;

import com.mysql.jdbc.Driver;
import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.net.ConnectException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class InputdatabarangSparepart extends javax.swing.JFrame {
  


/**public void kosongdata(){
txt_kodebrng.setText(null);
jComboBox1.setSelectedIndex(0);
txt_namabrng.setText(null);
txt_jumlah.setText(null);
txt_hargajual.setText(null);
txt_hargabeli.setText(null);
}*/
   public void kodebarang_auto(){
       try {
           Connection Koneksi= DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
           java.sql.Statement stat = Koneksi.createStatement();
           ResultSet rs = stat.executeQuery("SELECT * FROM tb_barang order by id_barang desc");
           if (rs.next()) {
               String kode=rs.getString("id_barang").substring(3);
               String AN = ""+ (Integer.parseInt(kode)+ 1);
               String Nol = "";
               if (AN.length()==1) 
                   {Nol="00";}
               else if(AN.length()==2)
               {Nol="0" ;}
               else if(AN.length()==3)
               {Nol="";}   
               txt_kodebrng.setText("BRS" +Nol+AN);
           } else {
               txt_kodebrng.setText("BRS001");
           }
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
       }
   
   }
    public InputdatabarangSparepart() {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
   setShape(new RoundRectangle2D.Double(0,0, getWidth(),getHeight(),27,27));  
  kodebarang_auto();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
*/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_kodebrng = new javax.swing.JTextField();
        txt_nama_jenis = new javax.swing.JTextField();
        txt_namabrng = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        txt_hargajual = new javax.swing.JTextField();
        txt_hargabeli = new javax.swing.JTextField();
        Selesai = new javax.swing.JLabel();
        Kembali = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_kodebrng.setEditable(false);
        txt_kodebrng.setBackground(new java.awt.Color(236, 239, 254));
        txt_kodebrng.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_kodebrng.setBorder(null);
        txt_kodebrng.setEnabled(false);
        getContentPane().add(txt_kodebrng, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 64, 238, 29));

        txt_nama_jenis.setBackground(new java.awt.Color(236, 239, 254));
        txt_nama_jenis.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_nama_jenis.setText("    Spare Part");
        txt_nama_jenis.setBorder(null);
        txt_nama_jenis.setEnabled(false);
        txt_nama_jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_jenisActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nama_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 107, 238, 29));

        txt_namabrng.setBackground(new java.awt.Color(236, 239, 254));
        txt_namabrng.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_namabrng.setBorder(null);
        getContentPane().add(txt_namabrng, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 151, 212, 28));

        txt_jumlah.setBackground(new java.awt.Color(236, 239, 254));
        txt_jumlah.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_jumlah.setBorder(null);
        getContentPane().add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 194, 212, 29));

        txt_hargajual.setBackground(new java.awt.Color(236, 239, 254));
        txt_hargajual.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_hargajual.setBorder(null);
        getContentPane().add(txt_hargajual, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 240, 212, 29));

        txt_hargabeli.setBackground(new java.awt.Color(236, 239, 254));
        txt_hargabeli.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_hargabeli.setBorder(null);
        getContentPane().add(txt_hargabeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 284, 212, 28));

        Selesai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Selesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelesaiMouseClicked(evt);
            }
        });
        getContentPane().add(Selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 50, 22));

        Kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Group 34 (2).png"))); // NOI18N
        Kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliMouseClicked(evt);
            }
        });
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/input data barng.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelesaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelesaiMouseClicked
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject", "root", "");
            try {
                String kodebarang = txt_kodebrng.getText();
                String namabarang =txt_namabrng.getText();
                Long.parseLong(txt_jumlah.getText());
                String hargajual = txt_hargajual.getText();
                String hargabeli = txt_hargabeli.getText();
   
       
                //Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject", "root", "");
                java.sql.Statement st = conn.createStatement();
                String query = "INSERT INTO tb_barang VALUES('" + kodebarang + "','Spare Part','" + namabarang + "','" + txt_jumlah.getText() + "','" + hargajual + "','" +  hargabeli + "')";
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Data Berhasil DiSimpan");
                kodebarang_auto();
                Dashboard.loadDataSparepart();
                dispose();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Masukkan data dengan benar" );
            }
        } catch (SQLException ex) {
                System.out.print("TERJADI KESALAHAN" + ex);
            }
            /**
           Koneksi connect = new Koneksi();
        connect.koneksi();
        PostSparepart post = new PostSparepart();


     String kodebarang = txt_kodebrng.getText();
        String namabarang =txt_namabrng.getText();
        int jumlah = Integer.parseInt(txt_jumlah.getText());
        int hargajual = Integer.parseInt(txt_hargajual.getText());
        int hargabeli = Integer.parseInt(txt_hargabeli.getText());
         String Jenis = txt_namabrng1.getText();
        post.post(kodebarang, Jenis, namabarang, jumlah, hargajual, hargabeli);
        Dashboard.loadDataSparepart();
        dispose();**/
    }//GEN-LAST:event_SelesaiMouseClicked

    private void txt_nama_jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_jenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_jenisActionPerformed

    private void KembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliMouseClicked
        // TODO add your handling code here:
     dispose();
    }//GEN-LAST:event_KembaliMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputdatabarangSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputdatabarangSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputdatabarangSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputdatabarangSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputdatabarangSparepart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Kembali;
    private javax.swing.JLabel Selesai;
    public javax.swing.JTextField txt_hargabeli;
    public javax.swing.JTextField txt_hargajual;
    public javax.swing.JTextField txt_jumlah;
    public javax.swing.JTextField txt_kodebrng;
    public javax.swing.JTextField txt_nama_jenis;
    public javax.swing.JTextField txt_namabrng;
    // End of variables declaration//GEN-END:variables
}
