/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pm.project;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class InputDataJasa extends javax.swing.JFrame {

     
    public InputDataJasa() {
        initComponents();
         Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
          int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
   setShape(new RoundRectangle2D.Double(0,0, getWidth(),getHeight(),27,27));
   int row = Dashboard.TableServis.getSelectedRow();
   Idservice.setText(Dashboard.TableServis.getValueAt(row, 0).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Idservice = new javax.swing.JTextField();
        NamaJasa = new javax.swing.JTextField();
        HargaJasa = new javax.swing.JTextField();
        Kembali = new javax.swing.JLabel();
        Selesai = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Idservice.setText("  ");
        Idservice.setBorder(null);
        Idservice.setEnabled(false);
        getContentPane().add(Idservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 83, 199, 24));

        NamaJasa.setBackground(new java.awt.Color(236, 239, 254));
        NamaJasa.setBorder(null);
        getContentPane().add(NamaJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 141, 187, 23));

        HargaJasa.setBackground(new java.awt.Color(236, 239, 254));
        HargaJasa.setBorder(null);
        getContentPane().add(HargaJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 196, 187, 25));

        Kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliMouseClicked(evt);
            }
        });
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 325, 75, 25));

        Selesai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Selesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelesaiMouseClicked(evt);
            }
        });
        getContentPane().add(Selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 325, 75, 25));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Input data jasa.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 402));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliMouseClicked
        dispose();
    }//GEN-LAST:event_KembaliMouseClicked

    private void SelesaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelesaiMouseClicked
        try {
Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
   try {
          String id=Idservice.getText();
          String nama_jasa = NamaJasa.getText();
          String Harga_jasa = HargaJasa.getText();
        
        java.sql.Statement st = conn.createStatement();
                String query = "INSERT INTO tb_jasa VALUES('"+id+"', '" + nama_jasa + "','"+ Harga_jasa + "')";
        st.executeUpdate(query);
        JOptionPane.showMessageDialog(null,"Data jasa berhasil ditambahkan");
        Dashboard.loadDatatransaksiservicejasa();
        dispose();
    }  catch(Exception e){
            JOptionPane.showMessageDialog(null,"Masukkan data dengan benar" );
            
    }
}     catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"Terjadi Kesalahan");
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_SelesaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputDataJasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputDataJasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputDataJasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputDataJasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputDataJasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField HargaJasa;
    private javax.swing.JTextField Idservice;
    private javax.swing.JLabel Kembali;
    private javax.swing.JTextField NamaJasa;
    private javax.swing.JLabel Selesai;
    // End of variables declaration//GEN-END:variables
}
