/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pm.project;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class InputDataKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form InputDataKaryawan
     */
          
          
    Koneksi connect = new Koneksi();
 
     public void idkar_auto(){
       try {
           Connection Koneksi= DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
           java.sql.Statement stat = Koneksi.createStatement();
           ResultSet rs = stat.executeQuery("SELECT * FROM tb_karyawan WHERE id_karyawan LIKE 'KR%' order by id_karyawan desc");
           if (rs.next()) {
               String kode=rs.getString("id_karyawan").substring(2);
               String AN = ""+ (Integer.parseInt(kode)+ 1);
               String Nol = "";
               if (AN.length()==1) 
                   {Nol="000";}
               else if(AN.length()==2)
               {Nol="00" ;}
               else if(AN.length()==3)
               {Nol="0";}   
               txt_idkaryawan.setText("KR" +Nol+AN);
           } else {
               txt_idkaryawan.setText("KR0001");
           }
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
       }}
       int mousepX;
       int mousepY;
    public InputDataKaryawan() {
        initComponents();
         Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
   setShape(new RoundRectangle2D.Double(0,0, getWidth(),getHeight(),27,27)); 
        txt_idkaryawan.setEnabled(false);
        idkar_auto();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_idkaryawan = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        cmb_jeniskelamin = new javax.swing.JComboBox<>();
        txt_nohp = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        tgllahir = new com.toedter.calendar.JDateChooser();
        selesai = new javax.swing.JLabel();
        Kembali = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_idkaryawan.setBackground(new java.awt.Color(236, 239, 254));
        txt_idkaryawan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_idkaryawan.setBorder(null);
        txt_idkaryawan.setEnabled(false);
        getContentPane().add(txt_idkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 53, 263, 32));

        txt_nama.setBackground(new java.awt.Color(236, 239, 254));
        txt_nama.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_nama.setBorder(null);
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 101, 240, 32));

        cmb_jeniskelamin.setBackground(new java.awt.Color(236, 239, 254));
        cmb_jeniskelamin.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmb_jeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        cmb_jeniskelamin.setBorder(null);
        cmb_jeniskelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_jeniskelaminActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_jeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 148, 265, 34));

        txt_nohp.setBackground(new java.awt.Color(236, 239, 254));
        txt_nohp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_nohp.setBorder(null);
        txt_nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nohpActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 198, 240, 30));

        txt_alamat.setBackground(new java.awt.Color(236, 239, 254));
        txt_alamat.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_alamat.setBorder(null);
        getContentPane().add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 246, 240, 30));

        txt_email.setBackground(new java.awt.Color(236, 239, 254));
        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_email.setBorder(null);
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 293, 240, 30));

        txt_username.setBackground(new java.awt.Color(236, 239, 254));
        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_username.setBorder(null);
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 389, 240, 30));

        txt_password.setBackground(new java.awt.Color(236, 239, 254));
        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_password.setBorder(null);
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 436, 240, 30));

        tgllahir.setBackground(new java.awt.Color(236, 239, 254));
        getContentPane().add(tgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 270, 32));

        selesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selesaiMouseClicked(evt);
            }
        });
        getContentPane().add(selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 70, 20));

        Kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliMouseClicked(evt);
            }
        });
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 489, 75, 23));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Input data karyawan (2).png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_jeniskelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_jeniskelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_jeniskelaminActionPerformed

    private void txt_nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nohpActionPerformed

    private void selesaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selesaiMouseClicked
        // TODO add your handling code here:
 try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject", "root", "");

            try{
                String id = txt_idkaryawan.getText();
                String nama = txt_nama.getText();
                String jk = cmb_jeniskelamin.getSelectedItem().toString();
                Long.parseLong(txt_nohp.getText());
                String alamat = txt_alamat.getText();
                String email = txt_email.getText();
                String tampilan = "yyyy-MM-dd";
                SimpleDateFormat fm = new SimpleDateFormat(tampilan);
                String tanggallahir = String.valueOf(fm.format(tgllahir.getDate()));
                String username = txt_username.getText();
                String password = txt_password.getText();

                java.sql.Statement st = conn.createStatement();
                String query = "INSERT INTO tb_karyawan VALUES('" +id + "','" +nama + "','" +jk + "','" +alamat + "','" +txt_nohp.getText()+ "','" +email + "','"+tanggallahir+"')";
                st.executeUpdate(query);
                String query1 = "INSERT INTO tb_akun VALUES('"+username+"', '" +password+ "','karyawan','"+id+"')";
                st.executeUpdate(query1);
                JOptionPane.showMessageDialog(null, "Data Berhasil DiSimpan");
                idkar_auto();
                Dashboard.loadDataKaryawan();
                dispose();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Masukkan data dengan benar" );
            }
            //String no_hp = txt_nohp.getText();
        } catch (SQLException ex) {
            System.out.print("TERJADI KESALAHAN" + ex);
        }
             
    }//GEN-LAST:event_selesaiMouseClicked

    private void KembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliMouseClicked
        // TODO add your handling code here:                
        dispose();
    }//GEN-LAST:event_KembaliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputDataKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Kembali;
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox<String> cmb_jeniskelamin;
    private javax.swing.JLabel selesai;
    private com.toedter.calendar.JDateChooser tgllahir;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_idkaryawan;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nohp;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

}
