
package pm.project;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class InputDatabaranglaptop extends javax.swing.JFrame {
    /**
     * Creates new form InputDatabaranglaptop
     */
      Koneksi connect = new Koneksi();
 

     public void kodebarang_auto(){
       try {
           Connection Koneksi= DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
           java.sql.Statement stat = Koneksi.createStatement();
           ResultSet rs = stat.executeQuery("SELECT * FROM tb_barang WHERE id_barang LIKE 'BRL%' order by id_barang desc");
           if (rs.next()) {
               String kode=rs.getString("id_barang").substring(3);
               String AN = ""+ (Integer.parseInt(kode)+ 1);
               String Nol = "";
               if (AN.length()==1) 
                   {Nol="00";}
               else if(AN.length()==2)
               {Nol="0" ;}
               else if(AN.length()==3)
               {Nol="";}   
               txt_kodebarang.setText("BRL" +Nol+AN);
           } else {
               txt_kodebarang.setText("BRL001");
           }
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
       }}
    public InputDatabaranglaptop() {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
          int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
   setShape(new RoundRectangle2D.Double(0,0, getWidth(),getHeight(),27,27)); 
   kodebarang_auto();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_kodebarang = new javax.swing.JTextField();
        txt_jenis = new javax.swing.JTextField();
        txt_namabarang = new javax.swing.JTextField();
        txt_processor = new javax.swing.JTextField();
        txt_GPU = new javax.swing.JTextField();
        txt_RAM = new javax.swing.JTextField();
        txt_warna = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        txt_hargajual = new javax.swing.JTextField();
        txt_hargabeli = new javax.swing.JTextField();
        selesai = new javax.swing.JLabel();
        KembaliLaptop = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_kodebarang.setBackground(new java.awt.Color(236, 239, 254));
        txt_kodebarang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_kodebarang.setBorder(null);
        txt_kodebarang.setEnabled(false);
        getContentPane().add(txt_kodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 68, 228, 31));

        txt_jenis.setEditable(false);
        txt_jenis.setBackground(new java.awt.Color(236, 239, 254));
        txt_jenis.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_jenis.setText("    Laptop");
        txt_jenis.setBorder(null);
        txt_jenis.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txt_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 114, 228, 31));

        txt_namabarang.setBackground(new java.awt.Color(236, 239, 254));
        txt_namabarang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_namabarang.setBorder(null);
        txt_namabarang.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txt_namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 161, 212, 31));

        txt_processor.setBackground(new java.awt.Color(236, 239, 254));
        txt_processor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_processor.setBorder(null);
        getContentPane().add(txt_processor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 208, 212, 31));

        txt_GPU.setBackground(new java.awt.Color(236, 239, 254));
        txt_GPU.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_GPU.setBorder(null);
        getContentPane().add(txt_GPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 257, 212, 31));

        txt_RAM.setBackground(new java.awt.Color(236, 239, 254));
        txt_RAM.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_RAM.setBorder(null);
        getContentPane().add(txt_RAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 309, 212, 31));

        txt_warna.setBackground(new java.awt.Color(236, 239, 254));
        txt_warna.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_warna.setBorder(null);
        getContentPane().add(txt_warna, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 354, 212, 31));

        txt_jumlah.setBackground(new java.awt.Color(236, 239, 254));
        txt_jumlah.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_jumlah.setBorder(null);
        getContentPane().add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 404, 212, 31));

        txt_hargajual.setBackground(new java.awt.Color(236, 239, 254));
        txt_hargajual.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_hargajual.setBorder(null);
        getContentPane().add(txt_hargajual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 453, 212, 31));

        txt_hargabeli.setBackground(new java.awt.Color(236, 239, 254));
        txt_hargabeli.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_hargabeli.setBorder(null);
        getContentPane().add(txt_hargabeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 498, 212, 31));

        selesai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selesaiMouseClicked(evt);
            }
        });
        getContentPane().add(selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 540, 64, 23));

        KembaliLaptop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KembaliLaptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliLaptopMouseClicked(evt);
            }
        });
        getContentPane().add(KembaliLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 542, 65, 20));

        Background.setBackground(new java.awt.Color(236, 239, 254));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/input data barng laptop (2).png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selesaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selesaiMouseClicked
        // TODO add your handling code here:
        
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject", "root", "");
            try{
                String kodebarang = txt_kodebarang.getText();
                String namabarang = txt_namabarang.getText();
                String processor = txt_processor.getText();
                String GPU = txt_GPU.getText();
                String RAM = txt_RAM.getText();
                String warna = txt_warna.getText();
                Long.parseLong(txt_jumlah.getText());
                String hargaBeli = txt_hargabeli.getText();
                String hargaJual = txt_hargajual.getText();
                
                
                java.sql.Statement st = conn.createStatement();
                String query = "INSERT INTO tb_barang VALUES('" + kodebarang + "','Laptop','" + namabarang + "','" + txt_jumlah.getText() + "','" + hargaJual + "','" +  hargaBeli + "')";
                st.executeUpdate(query);
                String query1 = "INSERT INTO tb_detail_barang VALUES('" + kodebarang + "','" + processor + "','" + GPU + "','" + RAM + "','" + warna + "')";
                st.executeUpdate(query1);
                JOptionPane.showMessageDialog(null, "Data Berhasil DiSimpan");
                kodebarang_auto();
                Dashboard.loadDataLaptop();
                dispose();
            }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Masukkan data dengan benar" );
        }
            } catch (SQLException ex) {
                System.out.print("TERJADI KESALAHAN" + ex);
            }
            
        
        /** Koneksi connect = new Koneksi();
       Dashboard updateTabel = new Dashboard();
        connect.koneksi();
        PostLaptop Post = new PostLaptop();


        String id_barang = txt_kodebarang.getText();
        String nama_jenis =txt_jenis.getText();
        String processor =txt_processor.getText();
        String GPU =txt_GPU.getText();
        int RAM =Integer.parseInt(txt_RAM.getText());
        String warna =txt_warna.getText();
        int jumlah = Integer.parseInt(txt_jumlah.getText());
        int hargajual = Integer.parseInt(txt_hargajual.getText());
        int hargabeli = Integer.parseInt(txt_hargabeli.getText());
         
        Post.post(id_barang, nama_jenis, processor, GPU, RAM,warna,jumlah,hargajual,hargabeli);
        updateTabel.loadDataLaptop();
        dispose();*/
    }//GEN-LAST:event_selesaiMouseClicked

    private void KembaliLaptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliLaptopMouseClicked
        // TODO add your handling code here:                
        dispose();
    }//GEN-LAST:event_KembaliLaptopMouseClicked

    /**String kodebarang = txt_kodebarang.getText();
        String jenis = txt_jenis.getText();
        String namabarang = txt_namabarang.getText();
        String processor = txt_processor.getText();
        String GPU = txt_GPU.getText();
        String RAM = txt_RAM.getText();
        String warna = txt_warna.getText();
        String jumlah = txt_jumlah.getText();
        String hargaBeli = txt_hargabeli.getText();
        String hargaJual = txt_hargajual.getText();
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputDatabaranglaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputDatabaranglaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputDatabaranglaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputDatabaranglaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputDatabaranglaptop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel KembaliLaptop;
    private javax.swing.JLabel selesai;
    private javax.swing.JTextField txt_GPU;
    private javax.swing.JTextField txt_RAM;
    private javax.swing.JTextField txt_hargabeli;
    private javax.swing.JTextField txt_hargajual;
    private javax.swing.JTextField txt_jenis;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_kodebarang;
    private javax.swing.JTextField txt_namabarang;
    private javax.swing.JTextField txt_processor;
    private javax.swing.JTextField txt_warna;
    // End of variables declaration//GEN-END:variables
}
