package pm.project;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import static pm.project.Dashboard.model;
import static pm.project.Dashboard.selectedbarangID;
import static pm.project.Dashboard.tabelTransaksi;
import static pm.project.Dashboard.txt_harga;
import static pm.project.Dashboard.txt_id_barang;
import static pm.project.Dashboard.txt_idpenjualan;
import static pm.project.Dashboard.txt_jumlah;
import static pm.project.Dashboard.txt_namabarang;
import static pm.project.Dashboard.txt_total;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class ListBarangService extends javax.swing.JFrame {
 static String selectedServiceID;
 
    public static void loadDataService(){
         String [] judul = {"Id Service","Nama klien","Nama barang","Keluhan","Tanggal mulai","Status","Nama Jasa","Harga"};
        model = new DefaultTableModel(judul,0);
        jTableservice.setModel(model);
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
            ResultSet rs = con.createStatement().executeQuery("SELECT tb_service.id_service,tb_client.nama_client,tb_service.nama_barang,tb_service.keluhan,tb_service.tgl_mulai,tb_service.tgl_selesai,tb_service.status, tb_jasa.nama_jasa, tb_jasa.Harga_jasa FROM tb_service JOIN tb_client ON tb_service.id_client=tb_client.id_client JOIN tb_jasa ON tb_service.id_service=tb_jasa.id_service;");
            while(rs.next()){
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(7),rs.getString(8),rs.getString(9)};
                model.addRow(data);
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
             
    //Menampilkan data dari database tb_barang ke tabel SparePart
   
    
    public ListBarangService() {
        initComponents();
         // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
          setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loadDataService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Pilih = new javax.swing.JLabel();
        batal = new javax.swing.JLabel();
        tombol1 = new javax.swing.JLabel();
        txt_cariLaptop = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableservice = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pilih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pilih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PilihMouseClicked(evt);
            }
        });
        jPanel1.add(Pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 110, 40));

        batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batalMouseClicked(evt);
            }
        });
        jPanel1.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 110, 40));

        tombol1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Kotak Deskripsi (2).png"))); // NOI18N
        jPanel1.add(tombol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));

        txt_cariLaptop.setBackground(new java.awt.Color(240, 240, 240));
        txt_cariLaptop.setText("Cari Berdasarkan Nama Barang");
        txt_cariLaptop.setBorder(null);
        txt_cariLaptop.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cariLaptopKaryawanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cariLaptopKaryawanFocusLost(evt);
            }
        });
        txt_cariLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariLaptopKaryawanActionPerformed(evt);
            }
        });
        txt_cariLaptop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariLaptopKaryawanKeyReleased(evt);
            }
        });
        jPanel1.add(txt_cariLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 244, 25));

        jTableservice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableservice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableserviceMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableservice);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 490, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Group 41 (2).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batalMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_batalMouseClicked

    private void PilihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PilihMouseClicked
        // TODO add your handling code here:
        int row = jTableservice.getSelectedRow();
        int rowjumlah = Dashboard.tabeltransaksiservice.getRowCount();
        String ids = jTableservice.getValueAt(row, 0).toString();
        String namaclient = jTableservice.getValueAt(row, 1).toString();
        String namabarang = jTableservice.getValueAt(row, 2).toString();
        String keluhan = jTableservice.getValueAt(row, 3).toString();
        String jasa = jTableservice.getValueAt(row, 6).toString();
        String harga = jTableservice.getValueAt(row, 7).toString();
        
    try{
        if (rowjumlah<1){
        
                String data []= {ids,namaclient,namabarang,keluhan,jasa,harga};
                Dashboard.modeltrs.addRow(data);
                Dashboard.totalBiayaService();
                Dashboard.txt_bayar2.setText("");
                Dashboard.txt_kembalian2.setText("");
                dispose();
        }else {
            int respon = JOptionPane.showConfirmDialog(this, "Anda sudah memasukkan data \nApakan ingin mengganti dengan yang ini?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(respon==JOptionPane.YES_OPTION){
                Dashboard.modeltrs.removeRow(0);
                String data []= {ids,namaclient,namabarang,keluhan,jasa,harga};
                Dashboard.modeltrs.addRow(data);
                Dashboard.totalBiayaService();
                Dashboard.txt_bayar2.setText("");
                Dashboard.txt_kembalian2.setText("");
                dispose();
            }if(respon==JOptionPane.NO_OPTION){
                dispose();
            }
            }//else {
//                String data []= {ids,namaclient,namabarang,keluhan,jasa,harga};
//                Dashboard.modeltrs.addRow(data);
//                Dashboard.totalBiayaService();
//                Dashboard.txt_bayar2.setText("");
//                Dashboard.txt_kembalian2.setText("");
//                dispose();
//            }
        
//        if (rowjumlah<1){
//        
//                String data []= {ids,namaclient,namabarang,keluhan,jasa,harga};
//                Dashboard.modeltrs.addRow(data);
//                Dashboard.totalBiayaService();
//                Dashboard.txt_bayar2.setText("");
//                Dashboard.txt_kembalian2.setText("");
//                dispose();
//        }
//        else{
//            String data []= {ids,namaclient,namabarang,keluhan,jasa,harga};
//            Dashboard.modeltrs.addRow(data);
//            Dashboard.totalBiayaService();
//            Dashboard.txt_bayar2.setText("");
//            Dashboard.txt_kembalian2.setText("");
//            dispose();
//        }
    }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Masukkan data dengan benar" );}
    
        
    }//GEN-LAST:event_PilihMouseClicked

    private void jTableserviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableserviceMouseClicked
        // TODO add your handling code here:
        // Memilih data yang ada di tabel Laptop
        int row = jTableservice.getSelectedRow();
        String id = jTableservice.getValueAt(row, 0).toString();
        this.selectedServiceID = id;     
        System.out.println(selectedServiceID);
    }//GEN-LAST:event_jTableserviceMouseClicked

    private void txt_cariLaptopKaryawanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariLaptopKaryawanKeyReleased
        // TODO add your handling code here:
       String [] judul = {"Kode Transaksi","Id Service","Nama klien","Nama barang","Keluhan","Tanggal mulai","Tanggal selesai","Status","Nama Jasa","Harga"};
        model = new DefaultTableModel(judul,0);
        jTableservice.setModel(model);
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
            ResultSet rs = con.createStatement().executeQuery("SELECT tb_service.id_service,tb_client.nama_client,tb_service.nama_barang,tb_service.keluhan,tb_service.tgl_mulai,tb_service.tgl_selesai,\n" +
"tb_service.status FROM tb_service JOIN tb_client ON tb_service.id_client=tb_client.id_client JOIN tb_jasa ON tb_service.id_service=tb_jasa.id_service;");
            while(rs.next()){
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)};
                model.addRow(data);
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_txt_cariLaptopKaryawanKeyReleased

    private void txt_cariLaptopKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariLaptopKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariLaptopKaryawanActionPerformed

    private void txt_cariLaptopKaryawanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariLaptopKaryawanFocusLost
        // TODO add your handling code here:
        if(txt_cariLaptop.getText().equals("")) {
            txt_cariLaptop.setText("Cari Berdasarkan Nama Barang");
            txt_cariLaptop.setForeground(new Color(153, 153, 153));
        } else {
            txt_cariLaptop.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_cariLaptopKaryawanFocusLost

    private void txt_cariLaptopKaryawanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariLaptopKaryawanFocusGained
        // TODO add your handling code here:
        if(txt_cariLaptop.getText().equals("Cari Berdasarkan Nama Barang")) {
            txt_cariLaptop.setText("");
            txt_cariLaptop.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_cariLaptopKaryawanFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListBarangService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListBarangService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListBarangService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListBarangService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListBarangService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pilih;
    private javax.swing.JLabel batal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTableservice;
    private javax.swing.JLabel tombol1;
    private javax.swing.JTextField txt_cariLaptop;
    // End of variables declaration//GEN-END:variables
}
