/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pm.project;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import static pm.project.Dashboard.model;
import static pm.project.Dashboard.tb_pembelianlaptop;
import static pm.project.Dashboard.tb_pilihclientbelisparepart;

/**
 *
 * @author ACER
 */
public class ListDataKlien extends javax.swing.JFrame {
static String selectedClientID;
    /**
     * Creates new form Listdatabarang
     */ public static void loadDataClient() {
        String [] judul = {"ID","Nama Klien","Alamat","No. HP",};
        model = new DefaultTableModel(judul,0);
        tabelklien.setModel(model);
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
            ResultSet rs = con.createStatement().executeQuery("SELECT * from tb_client");
            while(rs.next()){
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
                model.addRow(data);
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void kodeclient_auto(){
       int cb = Dashboard.tb_pilihclientbelisparepart.getRowCount();
         try {
           Connection Koneksi= DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
           java.sql.Statement stat = Koneksi.createStatement();
           ResultSet rs = stat.executeQuery("SELECT * FROM tb_client WHERE id_client LIKE 'CLI%' order by id_client desc");
           if (cb<1) {
               
               rs.next();
               String kode=rs.getString("id_client").substring(3);
               String AN = ""+ (Integer.parseInt(kode)+ 1);
               String Nol = "";
               if (AN.length()==1) 
                   {Nol="00";}
               else if(AN.length()==2)
               {Nol="0" ;}
               else if(AN.length()==3)
               {Nol="";}   
               txt_idclient.setText("CLI" +Nol+AN); 
           }else{txt_idclient.setText(Dashboard.tb_pilihclientbelisparepart.getValueAt(0, 0).toString());}
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
           dispose();
       }}
    public ListDataKlien() {
        initComponents();
         // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
          setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loadDataClient();
        kodeclient_auto();
        baru1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pilih1 = new javax.swing.JLabel();
        pilih0 = new javax.swing.JLabel();
        baru1 = new javax.swing.JLabel();
        baru0 = new javax.swing.JLabel();
        Pilihan = new javax.swing.JPanel();
        jPanelPilih = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelklien = new javax.swing.JTable();
        Pilihdata = new javax.swing.JLabel();
        Batal = new javax.swing.JLabel();
        tombol = new javax.swing.JLabel();
        txt_cariKlien = new javax.swing.JTextField();
        search = new javax.swing.JLabel();
        jPanelBaru = new javax.swing.JPanel();
        txt_idclient = new javax.swing.JTextField();
        txt_namaclient = new javax.swing.JTextField();
        txt_nohp = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        selesai1 = new javax.swing.JLabel();
        KembaliInputKlien1 = new javax.swing.JLabel();
        Background2 = new javax.swing.JLabel();
        DataKlien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(571, 402));
        jPanel2.setMinimumSize(new java.awt.Dimension(571, 402));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pilih1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/pilih1.png"))); // NOI18N
        jPanel2.add(pilih1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, 30));

        pilih0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/pilih0.png"))); // NOI18N
        pilih0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilih0MouseClicked(evt);
            }
        });
        jPanel2.add(pilih0, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, 30));

        baru1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/baru1.png"))); // NOI18N
        jPanel2.add(baru1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 30));

        baru0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/baru0.png"))); // NOI18N
        baru0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baru0MouseClicked(evt);
            }
        });
        jPanel2.add(baru0, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 30));

        Pilihan.setBackground(new java.awt.Color(255, 255, 255));
        Pilihan.setLayout(new java.awt.CardLayout());

        jPanelPilih.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPilih.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelklien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelklien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelklienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelklien);

        jPanelPilih.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 550, 270));

        Pilihdata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pilihdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PilihdataMouseClicked(evt);
            }
        });
        jPanelPilih.add(Pilihdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 110, 40));

        Batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BatalMouseClicked(evt);
            }
        });
        jPanelPilih.add(Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 110, 40));

        tombol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Kotak Deskripsi (2).png"))); // NOI18N
        jPanelPilih.add(tombol, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        txt_cariKlien.setBackground(new java.awt.Color(240, 240, 240));
        txt_cariKlien.setText("Cari Berdasarkan Nama");
        txt_cariKlien.setBorder(null);
        txt_cariKlien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cariKlienFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cariKlienFocusLost(evt);
            }
        });
        txt_cariKlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariKlienActionPerformed(evt);
            }
        });
        txt_cariKlien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKlienKeyReleased(evt);
            }
        });
        jPanelPilih.add(txt_cariKlien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 244, 25));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Search Barang (1).png"))); // NOI18N
        jPanelPilih.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Pilihan.add(jPanelPilih, "card2");

        jPanelBaru.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBaru.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_idclient.setBackground(new java.awt.Color(236, 239, 254));
        txt_idclient.setBorder(null);
        txt_idclient.setEnabled(false);
        txt_idclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idclientActionPerformed(evt);
            }
        });
        jPanelBaru.add(txt_idclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 63, 238, 29));

        txt_namaclient.setBackground(new java.awt.Color(236, 239, 254));
        txt_namaclient.setBorder(null);
        txt_namaclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaclientActionPerformed(evt);
            }
        });
        jPanelBaru.add(txt_namaclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 105, 215, 30));

        txt_nohp.setBackground(new java.awt.Color(236, 239, 254));
        txt_nohp.setBorder(null);
        txt_nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nohpActionPerformed(evt);
            }
        });
        jPanelBaru.add(txt_nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 149, 215, 30));

        txt_alamat.setBackground(new java.awt.Color(236, 239, 254));
        txt_alamat.setBorder(null);
        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });
        jPanelBaru.add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 197, 215, 74));

        selesai1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selesai1MouseClicked(evt);
            }
        });
        jPanelBaru.add(selesai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 329, 70, 21));

        KembaliInputKlien1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Group 34 (2).png"))); // NOI18N
        KembaliInputKlien1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliInputKlien1MouseClicked(evt);
            }
        });
        jPanelBaru.add(KembaliInputKlien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Input data klient.png"))); // NOI18N
        jPanelBaru.add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        Pilihan.add(jPanelBaru, "card3");

        jPanel2.add(Pilihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 570, 400));

        DataKlien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/DataKlien (1).png"))); // NOI18N
        jPanel2.add(DataKlien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cariKlienFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariKlienFocusGained
        if(txt_cariKlien.getText().equals("")) {
            txt_cariKlien.setText("Cari Berdasarkan Nama");
            txt_cariKlien.setForeground(new Color(153, 153, 153));
        } else {
            txt_cariKlien.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_cariKlienFocusGained

    private void txt_cariKlienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariKlienFocusLost
        if(txt_cariKlien.getText().equals("Cari Berdasarkan Nama")) {
            txt_cariKlien.setText("");
            txt_cariKlien.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txt_cariKlienFocusLost

    private void txt_cariKlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariKlienActionPerformed

    }//GEN-LAST:event_txt_cariKlienActionPerformed

    private void txt_cariKlienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKlienKeyReleased
        String [] judul = {"ID","Nama Client","Alamat","No HP"};
        model = new DefaultTableModel(judul,0);
        tabelklien.setModel(model);
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM tb_client WHERE nama_client LIKE '%"+txt_cariKlien.getText()+"%'");
            while(rs.next()){
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
                model.addRow(data);
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_cariKlienKeyReleased

    private void tabelklienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelklienMouseClicked
        // TODO add your handling code here:
                int row =tabelklien.getSelectedRow();
        String klien =tabelklien.getValueAt(row,0).toString();
        this.selectedClientID=klien;
    }//GEN-LAST:event_tabelklienMouseClicked

    private void PilihdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PilihdataMouseClicked
        // TODO add your handling code here:
             
        Dashboard.txt_id_clien.setText(selectedClientID);
        
        //Dashboard.idlist.remove(row);
        if(Dashboard.tb_pilihclientbelisparepart.getRowCount()>0){
        Dashboard.pilihclient();}
          dispose();
    }//GEN-LAST:event_PilihdataMouseClicked

    private void BatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BatalMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BatalMouseClicked

    private void txt_idclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idclientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idclientActionPerformed

    private void txt_namaclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaclientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaclientActionPerformed

    private void txt_nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nohpActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void selesai1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selesai1MouseClicked
        // TODO add your handling code here:
        Koneksi connect = new Koneksi();
        connect.koneksi();
        if(tb_pilihclientbelisparepart.getRowCount()<1){
            try {
            Long.parseLong (txt_nohp.getText());
            String kodeclient = txt_idclient.getText();
            String namaclient = txt_namaclient.getText();
            String alamat = txt_alamat.getText();
            String data[] = {kodeclient, namaclient, txt_nohp.getText(), alamat };
            Dashboard.modelcb.addRow(data);
            //Dashboard.idlist.add(kodeclient);
            Dashboard.txt_id_clien.setText("");
            dispose();
        }     catch (Exception ex){
            JOptionPane.showMessageDialog(null,"Masukkan Nomor HP dengan benar");
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }}else{
            int respon = JOptionPane.showConfirmDialog(this, "Anda sudah memasukkan client \n Apakan ingin memperbarui?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(respon==JOptionPane.YES_OPTION){
                try{
                    Long.parseLong(txt_nohp.getText());
                    try{
                        Dashboard.tb_pilihclientbelisparepart.setValueAt(txt_idclient.getText(), 0, 0);
                        Dashboard.tb_pilihclientbelisparepart.setValueAt(txt_namaclient.getText(), 0, 1);
                        Dashboard.tb_pilihclientbelisparepart.setValueAt(txt_nohp.getText(), 0, 2);
                        Dashboard.tb_pilihclientbelisparepart.setValueAt(txt_alamat.getText(), 0, 3);
                        JOptionPane.showMessageDialog(null,"Data client berhasil diedit");
                        dispose();
                    } 
                    catch(Exception e){
                    JOptionPane.showMessageDialog(this, "Terjadi kesalahan");
                }
                }
                catch (Exception ex){
                JOptionPane.showMessageDialog(this, "Masukkan data dengan benar");
        }
            }
        }
    }//GEN-LAST:event_selesai1MouseClicked

    private void KembaliInputKlien1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliInputKlien1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_KembaliInputKlien1MouseClicked

    private void pilih0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilih0MouseClicked

        try {
            baru1.setVisible(false);
            pilih1.setVisible(true);
            baru0.setVisible(true);
            //remove panel
            Pilihan.removeAll();
            Pilihan.repaint();
            Pilihan.revalidate();
            //add panel
            Pilihan.add(jPanelPilih);
            Pilihan.repaint();
            Pilihan.revalidate();
        } catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_pilih0MouseClicked

    private void baru0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baru0MouseClicked

        try {
            pilih1.setVisible(false);
            baru1.setVisible(true);
            pilih0.setVisible(true);
            //remove panel
            Pilihan.removeAll();
            Pilihan.repaint();
            Pilihan.revalidate();
            //add panel
            Pilihan.add(jPanelBaru);
            Pilihan.repaint();
            Pilihan.revalidate();
        } catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_baru0MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListDataKlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListDataKlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListDataKlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListDataKlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListDataKlien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background2;
    private javax.swing.JLabel Batal;
    private javax.swing.JLabel DataKlien;
    private javax.swing.JLabel KembaliInputKlien1;
    private javax.swing.JPanel Pilihan;
    private javax.swing.JLabel Pilihdata;
    private javax.swing.JLabel baru0;
    private javax.swing.JLabel baru1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBaru;
    private javax.swing.JPanel jPanelPilih;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pilih0;
    private javax.swing.JLabel pilih1;
    private javax.swing.JLabel search;
    private javax.swing.JLabel selesai1;
    private static javax.swing.JTable tabelklien;
    private javax.swing.JLabel tombol;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_cariKlien;
    private javax.swing.JTextField txt_idclient;
    private javax.swing.JTextField txt_namaclient;
    private javax.swing.JTextField txt_nohp;
    // End of variables declaration//GEN-END:variables
}
