package pm.project;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import static pm.project.Dashboard.model;
import static pm.project.Dashboard.selectedbarangID;
import static pm.project.Dashboard.tabelTransaksi;
import static pm.project.Dashboard.txt_harga;
import static pm.project.Dashboard.txt_id_barang;
import static pm.project.Dashboard.txt_idpenjualan;
import static pm.project.Dashboard.txt_namabarang;
import static pm.project.Dashboard.txt_total;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class ListdataBarang extends javax.swing.JFrame {
 static String selectedbarangID;
    static String selectedjenisbrgID;
    /**
     * Creates new form ListdataKLien
     */ //Menampilkan data dari database tb_barang dan tb_detail_barang ke tabel Laptop
    public  void loadDataLaptop(){
        String [] judul = {"ID","Nama barang","Processor","GPU","RAM","Warna","Jumlah","Harga jual", "Harga beli"};
        model = new DefaultTableModel(judul,0);
        tabelLaptop.setModel(model);
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
            ResultSet rs = con.createStatement().executeQuery(" SELECT tb_barang.id_barang,tb_barang.nama_barang,"
                    + "tb_detail_barang.processor,tb_detail_barang.GPU,tb_detail_barang.RAM,tb_detail_barang.Warna, tb_barang.kuantitas,"
                    + "tb_barang.harga_jual,tb_barang.harga_beli\n" +
            "FROM tb_barang INNER JOIN tb_detail_barang ON tb_barang.id_barang=tb_detail_barang.id_detail_barang where tb_barang.kuantitas > 0;");
            while(rs.next()){
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)
                ,rs.getString(8),rs.getString(9)};
                model.addRow(data);
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }}
             
    //Menampilkan data dari database tb_barang ke tabel SparePart
    public  void loadDataSparepart(){
       String [] judul = {"ID","Nama barang","Jumlah","Harga jual", "Harga beli"};
        model = new DefaultTableModel(judul,0);
        tabelSparepart.setModel(model);
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
            ResultSet rs = con.createStatement().executeQuery("SELECT id_barang,nama_barang,kuantitas,harga_jual,harga_beli from tb_barang where id_barang LIKE '%BRS%' and kuantitas > 0 ");
            while(rs.next()){
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                model.addRow(data);
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public ListdataBarang() {
        initComponents();
         // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
          setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loadDataLaptop();
        loadDataSparepart();
        Sparepart1.setVisible(false);
        tabelLaptop.fixTable(ScrollPanelLaptopedit);
        tabelSparepart.fixTable(ScrollPanelSparepartedit);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DataBarang = new javax.swing.JLabel();
        Laptop1 = new javax.swing.JLabel();
        Laptop0 = new javax.swing.JLabel();
        Sparepart1 = new javax.swing.JLabel();
        Sparepart0 = new javax.swing.JLabel();
        Pilihan = new javax.swing.JPanel();
        jPanelLaptop = new javax.swing.JPanel();
        txt_cariLaptop = new javax.swing.JTextField();
        SearchLaptop = new javax.swing.JLabel();
        Pilihdatalaptop = new javax.swing.JLabel();
        batalLaptop = new javax.swing.JLabel();
        tombol1 = new javax.swing.JLabel();
        txt_jumlah = new javax.swing.JTextField();
        ScrollPanelLaptopedit = new javax.swing.JScrollPane();
        tabelLaptop = new javaswingdev.swing.table.Table();
        jPanelSparepart = new javax.swing.JPanel();
        txt_cariSparePart = new javax.swing.JTextField();
        SearchLaptop1 = new javax.swing.JLabel();
        PilihdataSparepart = new javax.swing.JLabel();
        batalSparepart = new javax.swing.JLabel();
        tombol3 = new javax.swing.JLabel();
        txt_jumlah1 = new javax.swing.JTextField();
        ScrollPanelSparepartedit = new javax.swing.JScrollPane();
        tabelSparepart = new javaswingdev.swing.table.Table();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DataBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/DataBarang (1).png"))); // NOI18N
        jPanel1.add(DataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        Laptop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Group 73 (1).png"))); // NOI18N
        jPanel1.add(Laptop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, 30));

        Laptop0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Group 73.png"))); // NOI18N
        Laptop0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Laptop0MouseClicked(evt);
            }
        });
        jPanel1.add(Laptop0, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, 30));

        Sparepart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Group 74 (1).png"))); // NOI18N
        jPanel1.add(Sparepart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, 30));

        Sparepart0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Group 74.png"))); // NOI18N
        Sparepart0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sparepart0MouseClicked(evt);
            }
        });
        jPanel1.add(Sparepart0, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, 30));

        Pilihan.setBackground(new java.awt.Color(255, 255, 255));
        Pilihan.setLayout(new java.awt.CardLayout());

        jPanelLaptop.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLaptop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cariLaptop.setBackground(new java.awt.Color(240, 240, 240));
        txt_cariLaptop.setText("Cari Berdasarkan Nama");
        txt_cariLaptop.setBorder(null);
        txt_cariLaptop.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cariLaptopKaryawanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cariLaptopKaryawanFocusLost(evt);
            }
        });
        txt_cariLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariLaptopKaryawanActionPerformed(evt);
            }
        });
        txt_cariLaptop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariLaptopKaryawanKeyReleased(evt);
            }
        });
        jPanelLaptop.add(txt_cariLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 14, 244, 25));

        SearchLaptop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Search Barang (1).png"))); // NOI18N
        jPanelLaptop.add(SearchLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        Pilihdatalaptop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pilihdatalaptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PilihdatalaptopMouseClicked(evt);
            }
        });
        jPanelLaptop.add(Pilihdatalaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 110, 40));

        batalLaptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batalLaptopMouseClicked(evt);
            }
        });
        jPanelLaptop.add(batalLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 110, 40));

        tombol1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Kotak Deskripsi (2).png"))); // NOI18N
        jPanelLaptop.add(tombol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 240, -1));

        txt_jumlah.setBackground(new java.awt.Color(236, 239, 254));
        txt_jumlah.setText("Masukkan Jumlah");
        txt_jumlah.setBorder(null);
        txt_jumlah.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_jumlahFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_jumlahFocusLost(evt);
            }
        });
        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });
        jPanelLaptop.add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 180, 30));

        tabelLaptop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelLaptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelLaptopMouseClicked(evt);
            }
        });
        ScrollPanelLaptopedit.setViewportView(tabelLaptop);

        jPanelLaptop.add(ScrollPanelLaptopedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 520, 330));

        Pilihan.add(jPanelLaptop, "card2");

        jPanelSparepart.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSparepart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cariSparePart.setBackground(new java.awt.Color(240, 240, 240));
        txt_cariSparePart.setText("Cari Berdasarkan Nama");
        txt_cariSparePart.setBorder(null);
        txt_cariSparePart.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cariSparePartKaryawanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cariSparePartKaryawanFocusLost(evt);
            }
        });
        txt_cariSparePart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariSparePartKaryawanActionPerformed(evt);
            }
        });
        txt_cariSparePart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariSparePartKaryawanKeyReleased(evt);
            }
        });
        jPanelSparepart.add(txt_cariSparePart, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 14, 244, 25));

        SearchLaptop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Search Barang (1).png"))); // NOI18N
        jPanelSparepart.add(SearchLaptop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        PilihdataSparepart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PilihdataSparepart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PilihdataSparepartMouseClicked(evt);
            }
        });
        jPanelSparepart.add(PilihdataSparepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 110, 40));

        batalSparepart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batalSparepartMouseClicked(evt);
            }
        });
        jPanelSparepart.add(batalSparepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 110, 40));

        tombol3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Kotak Deskripsi (2).png"))); // NOI18N
        jPanelSparepart.add(tombol3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 240, -1));

        txt_jumlah1.setBackground(new java.awt.Color(236, 239, 254));
        txt_jumlah1.setText("Masukkan Jumlah");
        txt_jumlah1.setBorder(null);
        txt_jumlah1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_jumlah1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_jumlah1FocusLost(evt);
            }
        });
        txt_jumlah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlah1ActionPerformed(evt);
            }
        });
        jPanelSparepart.add(txt_jumlah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 180, 30));

        tabelSparepart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelSparepart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelSparepartMouseClicked(evt);
            }
        });
        ScrollPanelSparepartedit.setViewportView(tabelSparepart);

        jPanelSparepart.add(ScrollPanelSparepartedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 520, 330));

        Pilihan.add(jPanelSparepart, "card3");

        jPanel1.add(Pilihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 543, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cariLaptopKaryawanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariLaptopKaryawanFocusGained
        // TODO add your handling code here:
        if(txt_cariLaptop.getText().equals("Cari Berdasarkan Nama")) {
            txt_cariLaptop.setText("");
            txt_cariLaptop.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_cariLaptopKaryawanFocusGained

    private void txt_cariLaptopKaryawanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariLaptopKaryawanFocusLost
        // TODO add your handling code here:
        if(txt_cariLaptop.getText().equals("")) {
            txt_cariLaptop.setText("Cari Berdasarkan Nama");
            txt_cariLaptop.setForeground(new Color(153, 153, 153));
        } else {
            txt_cariLaptop.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_cariLaptopKaryawanFocusLost

    private void txt_cariLaptopKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariLaptopKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariLaptopKaryawanActionPerformed

    private void txt_cariLaptopKaryawanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariLaptopKaryawanKeyReleased
        // TODO add your handling code here:
        String [] judul = {"ID","Nama jenis","Nama barang","Processor","GPU","RAM","Warna","Jumlah","Harga jual", "Harga beli"};
        model = new DefaultTableModel(judul,0);
        tabelLaptop.setModel(model);
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
            ResultSet rs = con.createStatement().executeQuery("SELECT tb_barang.id_barang,tb_barang.nama_jenis,tb_barang.nama_barang, tb_detail_barang.processor,tb_detail_barang.GPU,tb_detail_barang.RAM,tb_detail_barang.Warna, tb_barang.kuantitas ,tb_barang.harga_jual,"
                + "tb_barang.harga_beli FROM tb_barang INNER JOIN tb_detail_barang ON tb_barang.id_barang=tb_detail_barang.id_detail_barang WHERE tb_barang.nama_barang LIKE '%"+txt_cariLaptop.getText()+"%'");
            while(rs.next()){
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)
                    ,rs.getString(8),rs.getString(9),rs.getString(10)};
                model.addRow(data);
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_cariLaptopKaryawanKeyReleased

    private void txt_cariSparePartKaryawanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariSparePartKaryawanFocusGained
        // TODO add your handling code here:
        if(txt_cariSparePart.getText().equals("Cari Berdasarkan Nama")) {
            txt_cariSparePart.setText("");
            txt_cariSparePart.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_cariSparePartKaryawanFocusGained

    private void txt_cariSparePartKaryawanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariSparePartKaryawanFocusLost

        if(txt_cariSparePart.getText().equals("")) {
            txt_cariSparePart.setText("Cari Berdasarkan Nama");
            txt_cariSparePart.setForeground(new Color(153, 153, 153));
        } else {
            txt_cariSparePart.setForeground(new Color(0, 0, 0));
        }// TODO add your handling code here:
    }//GEN-LAST:event_txt_cariSparePartKaryawanFocusLost

    private void txt_cariSparePartKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariSparePartKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariSparePartKaryawanActionPerformed

    private void txt_cariSparePartKaryawanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariSparePartKaryawanKeyReleased
        // TODO add your handling code here:
        String [] judul = {"ID","Nama jenis","Nama barang","Jumlah","Harga jual", "Harga beli"};
        model = new DefaultTableModel(judul,0);
        tabelSparepart.setModel(model);
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
            ResultSet rs = con.createStatement().executeQuery("SELECT * from tb_barang where id_barang LIKE '%BRS%' AND nama_barang LIKE '%"+txt_cariSparePart.getText()+"%'");
            while(rs.next()){
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)};
                model.addRow(data);
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_cariSparePartKaryawanKeyReleased

    private void PilihdatalaptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PilihdatalaptopMouseClicked
           // TODO add your handling code here:
        int i = tabelLaptop.getSelectedRow(),jumlah,total;
        
        String id = tabelLaptop.getValueAt(i, 0).toString();
        String nama = tabelLaptop.getValueAt(i, 1).toString();
        String harga = tabelLaptop.getValueAt(i, 7).toString();
        int jumlahtotal = Integer.valueOf(tabelLaptop.getValueAt(i, 6).toString());
        jumlah = Integer.valueOf(txt_jumlah.getText());
        
        if (jumlah<=jumlahtotal){
        Dashboard.txt_id_barang.setText(id);
        Dashboard.txt_namabarang.setText(nama);
        Dashboard.txt_harga.setText(harga);
        Dashboard.txt_jumlah.setText(txt_jumlah.getText().toString());
        
        total = jumlah * Integer.valueOf(harga);
//         Rupiah RP = new Rupiah();
//        txt_total.setText(String.valueOf(RP.formatRupiah(total).replace(",00", "")));
        txt_total.setText(String.valueOf(total));

        Dashboard.loadData();
        Dashboard.totalBiaya();
        Dashboard.totalBiayaTT();
        Dashboard.clear2();
        txt_id_barang.requestFocus();
        dispose();}
        else JOptionPane.showMessageDialog(null,"Jumlah melebihi stok");
    }//GEN-LAST:event_PilihdatalaptopMouseClicked
    private void batalLaptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batalLaptopMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_batalLaptopMouseClicked

    private void PilihdataSparepartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PilihdataSparepartMouseClicked
        // TODO add your handling code here:
          int i = tabelSparepart.getSelectedRow(), jumlah, total;
        
        String id = tabelSparepart.getValueAt(i, 0).toString();
        String nama = tabelSparepart.getValueAt(i, 1).toString();
        String harga = tabelSparepart.getValueAt(i, 3).toString();
        int jumlahtotal = Integer.valueOf(tabelSparepart.getValueAt(i, 2).toString());
        jumlah = Integer.valueOf(txt_jumlah1.getText());
        
        if (jumlah<=jumlahtotal){
        Dashboard.txt_id_barang.setText(id);
        Dashboard.txt_namabarang.setText(nama);
        Dashboard.txt_harga.setText(harga);
        Dashboard.txt_jumlah.setText(txt_jumlah1.getText().toString());
        total = jumlah * Integer.valueOf(harga);
        
          Rupiah RP = new Rupiah();
        txt_total.setText(String.valueOf(RP.formatRupiah(total).replace(",00", "")));
        Dashboard.loadData();
        Dashboard.totalBiaya();
        Dashboard.totalBiayaTT();
        Dashboard.clear2();
        txt_id_barang.requestFocus();
        dispose();
        }else JOptionPane.showMessageDialog(null,"Jumlah melebihi stok");
    }//GEN-LAST:event_PilihdataSparepartMouseClicked

    private void batalSparepartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batalSparepartMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_batalSparepartMouseClicked

    private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlahActionPerformed

    private void txt_jumlah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlah1ActionPerformed

    private void tabelLaptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelLaptopMouseClicked
        // Memilih data yang ada di tabel Laptop
        int row = tabelLaptop.getSelectedRow();
        String client = tabelLaptop.getValueAt(row, 0).toString();
        this.selectedbarangID = client;
        String jenis = tabelLaptop.getValueAt(row, 1).toString();
        this.selectedjenisbrgID = jenis;
    }//GEN-LAST:event_tabelLaptopMouseClicked

    private void tabelSparepartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelSparepartMouseClicked
         // Memilih data yang ada di tabel Spare part
        int row = tabelSparepart.getSelectedRow();
        String client = tabelSparepart.getValueAt(row, 0).toString();
        this.selectedbarangID = client;
        String jenis = tabelSparepart.getValueAt(row, 1).toString();
        this.selectedjenisbrgID = jenis;
    }//GEN-LAST:event_tabelSparepartMouseClicked

    private void txt_jumlah1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_jumlah1FocusGained
        if(txt_jumlah1.getText().equals("Masukkan Jumlah")) {
            txt_jumlah1.setText("");
            txt_jumlah1.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_jumlah1FocusGained

    private void txt_jumlah1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_jumlah1FocusLost
        if(txt_jumlah1.getText().equals("")) {
            txt_jumlah1.setText("Masukkan Jumlah");
            txt_jumlah1.setForeground(new Color(153, 153, 153));
        } else {
            txt_jumlah1.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_jumlah1FocusLost

    private void txt_jumlahFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_jumlahFocusGained
        if(txt_jumlah.getText().equals("Masukkan Jumlah")) {
            txt_jumlah.setText("");
            txt_jumlah.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_jumlahFocusGained

    private void txt_jumlahFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_jumlahFocusLost
        if(txt_jumlah.getText().equals("")) {
            txt_jumlah.setText("Masukkan Jumlah");
            txt_jumlah.setForeground(new Color(153, 153, 153));
        } else {
            txt_jumlah.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_jumlahFocusLost

    private void Laptop0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Laptop0MouseClicked

        try {
            Sparepart1.setVisible(false);
            Laptop1.setVisible(true);
            Sparepart0.setVisible(true);
            //remove panel
            Pilihan.removeAll();
            Pilihan.repaint();
            Pilihan.revalidate();
            //add panel
            Pilihan.add(jPanelLaptop);
            Pilihan.repaint();
            Pilihan.revalidate();
        } catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_Laptop0MouseClicked

    private void Sparepart0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sparepart0MouseClicked

        try {
            Laptop1.setVisible(false);
            Sparepart1.setVisible(true);
            Laptop0.setVisible(true);
            //remove panel
            Pilihan.removeAll();
            Pilihan.repaint();
            Pilihan.revalidate();
            //add panel
            Pilihan.add(jPanelSparepart);
            Pilihan.repaint();
            Pilihan.revalidate();
        } catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_Sparepart0MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListdataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListdataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListdataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListdataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListdataBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DataBarang;
    private javax.swing.JLabel Laptop0;
    private javax.swing.JLabel Laptop1;
    private javax.swing.JPanel Pilihan;
    private javax.swing.JLabel PilihdataSparepart;
    private javax.swing.JLabel Pilihdatalaptop;
    private javax.swing.JScrollPane ScrollPanelLaptopedit;
    private javax.swing.JScrollPane ScrollPanelSparepartedit;
    private javax.swing.JLabel SearchLaptop;
    private javax.swing.JLabel SearchLaptop1;
    private javax.swing.JLabel Sparepart0;
    private javax.swing.JLabel Sparepart1;
    private javax.swing.JLabel batalLaptop;
    private javax.swing.JLabel batalSparepart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelLaptop;
    private javax.swing.JPanel jPanelSparepart;
    private javaswingdev.swing.table.Table tabelLaptop;
    private javaswingdev.swing.table.Table tabelSparepart;
    private javax.swing.JLabel tombol1;
    private javax.swing.JLabel tombol3;
    private javax.swing.JTextField txt_cariLaptop;
    private javax.swing.JTextField txt_cariSparePart;
    public static javax.swing.JTextField txt_jumlah;
    public static javax.swing.JTextField txt_jumlah1;
    // End of variables declaration//GEN-END:variables
}
