/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pm.project;
import com.sbix.jnotify.NPosition;
import com.sbix.jnotify.NoticeType;
import com.sbix.jnotify.NoticeWindow;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Font;
import java.awt.TextField;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JTextField;
/**
 *
 * @author ACER
 */
public class LOGIN extends javax.swing.JFrame {
 int mousepX;
       int mousepY;
   public void addplaceholderStyle(JTextField textField){
   Font font = textField.getFont();
   font =font.deriveFont(Font.ITALIC);
   textField.setFont(font);
   textField.setForeground(Color.GRAY);
   }
    public void removeplaceholderStyle(JTextField textField){
    Font font = textField.getFont();
   font =font.deriveFont(Font.PLAIN|font.PLAIN);
   textField.setFont(font);
   textField.setForeground(Color.BLACK);
    };
    public LOGIN() {
      
        initComponents();
         Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        addplaceholderStyle(txt_user);
        addplaceholderStyle(txt_pass);
        setShape(new RoundRectangle2D.Double(0,0, getWidth(),getHeight(),20,20));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        txt_user = new javax.swing.JTextField();
        Iconpass = new javax.swing.JLabel();
        Iconuser = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 352, 340, 33));

        txt_pass.setBackground(new java.awt.Color(249, 252, 254));
        txt_pass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_pass.setText("Enter your Password");
        txt_pass.setBorder(null);
        txt_pass.setEchoChar('\u0000');
        txt_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passFocusLost(evt);
            }
        });
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 207, 340, 30));

        txt_user.setBackground(new java.awt.Color(249, 252, 254));
        txt_user.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_user.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_user.setText("Enter your Username");
        txt_user.setBorder(null);
        txt_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_userFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_userFocusLost(evt);
            }
        });
        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });
        txt_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_userKeyTyped(evt);
            }
        });
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 143, 340, 30));

        Iconpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/key-3-24 (1).png"))); // NOI18N
        getContentPane().add(Iconpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 203, 28, 30));

        Iconuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/guest-24.png"))); // NOI18N
        getContentPane().add(Iconuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 139, 25, 30));
        getContentPane().add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 23, 10));

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 25, 30));

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 40));

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/baseline_visibility_black_24dp.png"))); // NOI18N
        icon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon1MousePressed(evt);
            }
        });
        getContentPane().add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, 20));

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/baseline_visibility_off_black_24dp.png"))); // NOI18N
        icon2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon2MousePressed(evt);
            }
        });
        getContentPane().add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, 20));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Login.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 539));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        // TODO add your handling code here:
           try {
            String sql = "SELECT * FROM tb_akun WHERE username ='"+txt_user.getText()
                    +"'AND password ='"+txt_pass.getText()+"'";
            java.sql.Connection conn= CONFIG.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs =pst.executeQuery(sql);
            if(rs.next()){
                Dashboard.txt_idkaryawan.setText(rs.getString(4));
                
                if(txt_user.getText().equals(rs.getString("username"))
                        && txt_pass.getText().equals(rs.getString("password"))){                
                   Dashboard.txt_level.setText(rs.getString(3));
                    this.setVisible(false);                    
                    new Dashboard().setVisible(true);
                    new NoticeWindow(NoticeType.WARNING_NOTIFICATION,"Anda berhasil login",
                 NoticeWindow.SHORT_DELAY,NPosition.TOP_RIGHT);
                    
                }
            }else{
                new NoticeWindow(NoticeType.ERROR_NOTIFICATION,"   Username dan password salah",
                 NoticeWindow.SHORT_DELAY,NPosition.TOP_RIGHT);
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_LoginMouseClicked

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        try {
            String sql = "SELECT * FROM tb_akun WHERE username ='"+txt_user.getText()
                    +"'AND password ='"+txt_pass.getText()+"'";
            java.sql.Connection conn= CONFIG.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs =pst.executeQuery(sql);
            if(rs.next()){
                Dashboard.txt_idkaryawan.setText(rs.getString(4));
                Dashboard.txt_level.setText(rs.getString(3));
                if(txt_user.getText().equals(rs.getString("username"))
                        && txt_pass.getText().equals(rs.getString("password"))){                
                   
                    this.setVisible(false);                    
                    new Dashboard().setVisible(true);
                    new NoticeWindow(NoticeType.WARNING_NOTIFICATION,"Anda berhasil login",
                 NoticeWindow.SHORT_DELAY,NPosition.TOP_RIGHT);
                    
                }
            }else{
                new NoticeWindow(NoticeType.ERROR_NOTIFICATION,"   Username dan password salah",
                 NoticeWindow.SHORT_DELAY,NPosition.TOP_RIGHT);
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_txt_passActionPerformed

    private void txt_userKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyTyped
        // TODO add your handling code here:
   
    }//GEN-LAST:event_txt_userKeyTyped

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    private void txt_userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_userFocusGained
        // TODO add your handling code here:
        if (txt_user.getText().equals("Enter your Username")) {
            txt_user.setText(null);
            txt_user.requestFocus();
            removeplaceholderStyle(txt_user);
        }
    }//GEN-LAST:event_txt_userFocusGained

    private void txt_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passFocusGained
        // TODO add your handling code here:
        if (txt_pass.getText().equals("Enter your Password")) {
            txt_pass.setText(null);
            txt_pass.requestFocus();
            txt_pass.setEchoChar('*');
            removeplaceholderStyle(txt_pass);
        }
    }//GEN-LAST:event_txt_passFocusGained

    private void txt_userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_userFocusLost
        // TODO add your handling code here:
        if (txt_user.getText().length()==0) {
            addplaceholderStyle(txt_user);
            txt_user.setText("Enter your Username");
        }
    }//GEN-LAST:event_txt_userFocusLost

    private void txt_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passFocusLost
        // TODO add your handling code here:
         if (txt_pass.getText().length()==0) {
            addplaceholderStyle(txt_pass);
            txt_pass.setText("Enter your Password");
        }
    }//GEN-LAST:event_txt_passFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
        int koordinatX=evt.getXOnScreen();
        int koordinatY=evt.getYOnScreen();
        this.setLocation(koordinatX-mousepX,koordinatY-mousepY);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
       // TODO add your handling code here:
       mousepX = evt.getX();
       mousepY = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void icon2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MousePressed
        icon1.setVisible(true);
        icon2.setVisible(false);
        txt_pass.setEchoChar('*');
    }//GEN-LAST:event_icon2MousePressed

    private void icon1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MousePressed
        icon2.setVisible(true);
        icon1.setVisible(false);
        txt_pass.setEchoChar((char)0);
    }//GEN-LAST:event_icon1MousePressed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog(null, "do you want to close the app?"," "
            ,JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
        System.exit(0);
        }
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Iconpass;
    private javax.swing.JLabel Iconuser;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel close;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
