/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pm.project;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static pm.project.Dashboard.model;

/**
 *
 * @author ACER
 */
public class PilihBarangReturn extends javax.swing.JFrame {

    public void kodereturn_auto(){
       try {
           Connection Koneksi= DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
           java.sql.Statement stat = Koneksi.createStatement();
           ResultSet rs = stat.executeQuery("SELECT * FROM tb_return order by id_return desc");
           if (rs.next()) {
               String kode=rs.getString("id_return").substring(3);
               String AN = ""+ (Integer.parseInt(kode)+ 1);
               String Nol = "";
               if (AN.length()==1) 
                   {Nol="00";}
               else if(AN.length()==2)
               {Nol="0" ;}
               else if(AN.length()==3)
               {Nol="";}   
               idReturn.setText("RTN" +Nol+AN);
           } else {
               idReturn.setText("RTN001");
           }
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
       }}
    public PilihBarangReturn() {
        initComponents();
        String [] judul = {"ID Transaksi","Nama Barang","Tgl Penjualan","Garansi"};
        model = new DefaultTableModel(judul,0);
        pilihanreturn.setModel(model);
        kodereturn_auto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idTransaksi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pilihanreturn = new javax.swing.JTable();
        keluhan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        idReturn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        idTransaksi.setText("Masukkan ID Transaksi");
        idTransaksi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idTransaksiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idTransaksiFocusLost(evt);
            }
        });
        idTransaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idTransaksiKeyReleased(evt);
            }
        });

        pilihanreturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pilihanreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilihanreturnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pilihanreturn);

        keluhan.setText("Masukkan Keluhan");
        keluhan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                keluhanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                keluhanFocusLost(evt);
            }
        });

        jButton1.setText("Kembali");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });

        idReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(idReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(keluhan, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(171, 171, 171)
                            .addComponent(simpan))
                        .addComponent(idTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(idReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(keluhan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(idTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(120, 120, 120)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1)
                        .addComponent(simpan))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTransaksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTransaksiKeyReleased
        String [] judul = {"ID Transaksi","Nama Barang","Tgl Penjualan","Garansi"};
        model = new DefaultTableModel(judul,0);
        pilihanreturn.setModel(model);
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
            ResultSet rs = con.createStatement().executeQuery("SELECT tb_detail_penjualan.id_penjualan, tb_barang.nama_barang,tb_penjualan.tgl_penjualan,tb_penjualan.garansi FROM tb_penjualan INNER JOIN tb_detail_penjualan ON tb_penjualan.id_penjualan=tb_detail_penjualan.id_penjualan INNER JOIN tb_barang ON tb_detail_penjualan.id_barang=tb_barang.id_barang where tb_penjualan.id_penjualan='"+idTransaksi.getText()+"';");
            while(rs.next()){
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
                model.addRow(data);
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_idTransaksiKeyReleased

    private void idTransaksiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTransaksiFocusGained
        if(idTransaksi.getText().equals("Masukkan ID Transaksi")) {
            idTransaksi.setText("");
            idTransaksi.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_idTransaksiFocusGained

    private void idTransaksiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTransaksiFocusLost
        if(idTransaksi.getText().equals("")) {
            idTransaksi.setText("Masukkan ID Transaksi");
            idTransaksi.setForeground(new Color(153,153, 153));
        } else {
            idTransaksi.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_idTransaksiFocusLost

    private void keluhanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keluhanFocusGained
        if(keluhan.getText().equals("Masukkan Keluhan")) {
            keluhan.setText("");
            keluhan.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_keluhanFocusGained

    private void keluhanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keluhanFocusLost
        if(keluhan.getText().equals("")) {
            keluhan.setText("Masukkan Keluhan");
            keluhan.setForeground(new Color(153,153, 153));
        } else {
            keluhan.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_keluhanFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        Koneksi connect = new Koneksi();
       connect.koneksi();
try {
Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
   try {
        int row = pilihanreturn.getSelectedRow();
        String idreturn = idReturn.getText();
        String idtransaksi = pilihanreturn.getValueAt(row, 0).toString();
        String nama = pilihanreturn.getValueAt(row, 1).toString();
        String Keluhan = keluhan.getText();
        
        java.sql.Statement st = conn.createStatement();
        String query = "INSERT INTO tb_return VALUES('"+idreturn+"', '" + idtransaksi + "','"+ nama + "','"+Keluhan+"',now(),null,'Proses',null)";
        st.executeUpdate(query);
        JOptionPane.showMessageDialog(null,"Data Return berhasil ditambahkan");
        kodereturn_auto();
        Dashboard.loadDatareturn();
        dispose();
    }  catch(Exception e){
            JOptionPane.showMessageDialog(null,"Masukkan data dengan benar" );
            
    }
}     catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"Terjadi Kesalahan");
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_simpanMouseClicked

    private void idReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idReturnActionPerformed

    private void pilihanreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilihanreturnMouseClicked
        int row = pilihanreturn.getSelectedRow();
        int garansi = Integer.valueOf(pilihanreturn.getValueAt(row, 3).toString());
        int g = garansi*30;
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyy-MM-dd");
        String date = pilihanreturn.getValueAt(row, 2).toString();
        
        LocalDate tglpilihan = LocalDate.parse(date, formatter);
	LocalDate now = LocalDate.now();
        //Period diff = Period.between(tglpilihan, now);
        long days = ChronoUnit.DAYS.between(tglpilihan, now);
        if (g<days){
            System.out.println("garansi hangus");
            JOptionPane.showMessageDialog(null,"Garansi Hangus" );
            simpan.setVisible(false);
        }else {System.out.println("garansi berlaku");
                JOptionPane.showMessageDialog(null,"Garansi Aktif" );
                        simpan.setVisible(true);}
        
    }//GEN-LAST:event_pilihanreturnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihBarangReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihBarangReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihBarangReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihBarangReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihBarangReturn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idReturn;
    private javax.swing.JTextField idTransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField keluhan;
    private javax.swing.JTable pilihanreturn;
    private javax.swing.JButton simpan;
    // End of variables declaration//GEN-END:variables
}
