package pm.project;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import static pm.project.Dashboard.model;
import static pm.project.Dashboard.selectedbarangID;
import static pm.project.Dashboard.tabelTransaksi;
import static pm.project.Dashboard.txt_harga;
import static pm.project.Dashboard.txt_id_barang;
import static pm.project.Dashboard.txt_idpenjualan;
import static pm.project.Dashboard.txt_jumlah;
import static pm.project.Dashboard.txt_namabarang;
import static pm.project.Dashboard.txt_total;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class RiwayatReturn extends javax.swing.JFrame {
 static String selectedbarangID;
    static String selectedjenisbrgID;
    /**
     * Creates new form ListdataKLien
     */ //Menampilkan data dari database tb_barang dan tb_detail_barang ke tabel Laptop
    public static void loadDataLaptop(){
        String [] judul = {"Id Return","Id Penjualan","Nama","Keluhan","Masuk","Keluar","cost",};
        model = new DefaultTableModel(judul,0);
        tb_returntutup.setModel(model);
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
            ResultSet rs = con.createStatement().executeQuery(" SELECT * from tb_return where status = 'Tutup' ");
            while(rs.next()){
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(8)};
                model.addRow(data);
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }}
             
    //Menampilkan data dari database tb_barang ke tabel SparePart
    
    
    public RiwayatReturn() {
        initComponents();
         // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
          setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loadDataLaptop();
        tb_returntutup.fixTable(jScrollPane1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DataBarang = new javax.swing.JLabel();
        txt_cariReturn = new javax.swing.JTextField();
        SearchLaptop2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_returntutup = new javaswingdev.swing.table.Table();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DataBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/DataBarang (1).png"))); // NOI18N
        jPanel1.add(DataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txt_cariReturn.setBackground(new java.awt.Color(240, 240, 240));
        txt_cariReturn.setText("Cari Berdasarkan Nama Barang");
        txt_cariReturn.setBorder(null);
        txt_cariReturn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cariReturnKaryawanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cariReturnKaryawanFocusLost(evt);
            }
        });
        txt_cariReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariReturnKaryawanActionPerformed(evt);
            }
        });
        txt_cariReturn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariReturnKaryawanKeyReleased(evt);
            }
        });
        jPanel1.add(txt_cariReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 244, 25));

        SearchLaptop2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/project/PROPERTI/Search Barang (1).png"))); // NOI18N
        jPanel1.add(SearchLaptop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        tb_returntutup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_returntutup);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 500, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cariReturnKaryawanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariReturnKaryawanFocusGained
        if(txt_cariReturn.getText().equals("Cari Berdasarkan Nama Barang")) {
            txt_cariReturn.setText("");
            txt_cariReturn.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_cariReturnKaryawanFocusGained

    private void txt_cariReturnKaryawanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariReturnKaryawanFocusLost
        if(txt_cariReturn.getText().equals("")) {
            txt_cariReturn.setText("Cari Berdasarkan Nama Barang");
            txt_cariReturn.setForeground(new Color(153,153, 153));
        } else {
            txt_cariReturn.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_cariReturnKaryawanFocusLost

    private void txt_cariReturnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariReturnKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariReturnKaryawanActionPerformed

    private void txt_cariReturnKaryawanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariReturnKaryawanKeyReleased
        String [] judul = {"ID Return","ID Penjualan","Nama","Keluhan","Masuk","Keluar","cost",};
        model = new DefaultTableModel(judul,0);
        tb_returntutup.setModel(model);
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmproject","root","");
            ResultSet rs = con.createStatement().executeQuery(" SELECT * from tb_return where nama_barang LIKE '%"+txt_cariReturn.getText()+"%' and status = 'Tutup' ");
            while(rs.next()){
                String data [] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(8)};
                model.addRow(data);
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_cariReturnKaryawanKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatReturn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DataBarang;
    private javax.swing.JLabel SearchLaptop2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javaswingdev.swing.table.Table tb_returntutup;
    private javax.swing.JTextField txt_cariReturn;
    // End of variables declaration//GEN-END:variables
}
